### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by NakiriFox** [Owen3H/IntroTweaks#11]
[16:08:06.8834808] [Error  :IntroTweaks] An error occurred patching the menu. SAJ.
System.NullReferenceException: Object reference not set to an instance of an object
  at IntroTweaks.Patches.MenuManagerPatch.PatchMenu () [0x000f0] in <8d5bc23c7d854d0398bc7041de89ed14>:IL_00F0

**Comment by Owen3H** [comment]
If the mod continues to work, this is likely a harmless error that I'm working on silencing or making into a warning.
If it doesn't, it's likely another conflicting mod like Emblem - in which case there is nothing much I can do other than making IT run before everything else which could potentially introduce more problems.

I will always advocate that other mods copy and manipulate an element instead of doing things with the original.

If you don't want IntroTweaks to handle anything menu related, simply turn off all menu tweak options in the config, namely any that begin with `bFix` (others are less likely but still possible).
